apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: media-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/737764647544/secrets/service-principal-app/versions/1"
        path: "service-principal-app.json"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-gateway-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/737764647544/secrets/google-auth-client-secret/versions/2"
        path: "auth-client-secret.txt"
