apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: media-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/737764647544/secrets/service-principal-app/versions/1"
        path: "service-principal-app.json"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-gateway-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/737764647544/secrets/google-auth-client-secret/versions/2"
        path: "auth-client-secret.txt"

--- 

apiVersion: v1
kind: Secret
metadata:
  name: database-ip
type: Opaque
data:
  DATABASE_IP: 10.59.96.22 # Base64 encoded value of "10.59.96.20"

---

apiVersion: v1
kind: Secret
metadata:
  name: redis-ip
type: Opaque
data:
  REDIS_IP: 10.59.97.3 # Base64 encoded value of "10.59.96.20"
