apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: media-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/953454344870/secrets/service-principal-app/versions/1"
        path: "service-principal-app.json"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-gateway-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/953454344870/secrets/google-auth-client-secret/versions/1"
        path: "auth-client-secret.txt"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloud-trace-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/953454344870/secrets/cloud-trace-agent-sa-key/versions/1"
        path: "cloud-trace-key.json"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloud-profiler-secret
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/953454344870/secrets/cloud-profiler-agent-sa-key/versions/1"
        path: "cloud-profiler-key.json"