ingress:
  forceSSL: false  # Set to true to enable SSL redirection
  rules:
    - host: stagingapi.dkkom.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: api-gateway-service
            port: 8080
        - path: /cave
          pathType: Prefix
          service:
            name: cave-service
            port: 8080
        - path: /message
          pathType: Prefix
          service:
            name: message-service
            port: 8080
    - host: dkkom.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 80
    - host: stagingcdn.dkkom.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: media-service
            port: 8080
